ARG PORT="${PORT}" \
  NODE_ENV="${NODE_ENV}" \
  CLIENT_BASE_URL="${CLIENT_BASE_URL}" \
  DATABASE_HOST="${DATABASE_HOST}" \
  DATABASE_PORT="${DATABASE_PORT}" \
  DATABASE_USER="${DATABASE_USER}" \
  DATABASE_PASSWORD="${DATABASE_PASSWORD}" \
  DATABASE_NAME="${DATABASE_NAME}" \
  DATABASE_URL="postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}" \
  JWT_ACCESS_SECRET="${JWT_ACCESS_SECRET}" \
  JWT_REFRESH_SECRET="${JWT_REFRESH_SECRET}" \
  JWT_PASSWORD_RESET_SECRET="${JWT_PASSWORD_RESET_SECRET}" \
  REDIS_HOST="${REDIS_HOST}" \
  REDIS_PORT="${REDIS_PORT}" \
  REDIS_PASSWORD="${REDIS_PASSWORD}" \
  BUCKET_KEY="${BUCKET_KEY}" \
  BUCKET_SECRET="${BUCKET_SECRET}" \
  BUCKET_ENDPOINT="${BUCKET_ENDPOINT}" \
  BUCKET_NAME="${BUCKET_NAME}" \
  MAIL_HOST="${MAIL_HOST}" \
  MAIL_USER="${MAIL_USER}" \
  MAIL_PASSWORD="${MAIL_PASSWORD}" \
  MAIL_FROM="${MAIL_FROM}" \
  MAIL_PORT="${MAIL_PORT}" \
  YANDEX_CLIENT_ID="${YANDEX_CLIENT_ID}" \
  YANDEX_CLIENT_SECRET="${YANDEX_CLIENT_SECRET}" \
  YANDEX_BASE_URL="${YANDEX_BASE_URL}" \
  YANDEX_LOGIN_URL="${YANDEX_LOGIN_URL}"


FROM node:20.11-alpine AS builder

WORKDIR /var/www

COPY package.json ./

RUN yarn install

COPY . .

RUN yarn build

FROM node:20.11-alpine

WORKDIR /var/www

COPY --from=builder /var/www/node_modules ./node_modules
COPY --from=builder /var/www/dist ./dist
COPY --from=builder /var/www/src/db/drizzle/migrations ./dist/db/drizzle/migrations
COPY --from=builder /var/www/yarn.lock .
COPY --from=builder /var/www/docker-start-db.sh .

COPY package.json ./


ENV PORT="${PORT}" \
  NODE_ENV="${NODE_ENV}" \
  CLIENT_BASE_URL="${CLIENT_BASE_URL}" \
  DATABASE_HOST="${DATABASE_HOST}" \
  DATABASE_PORT="${DATABASE_PORT}" \
  DATABASE_USER="${DATABASE_USER}" \
  DATABASE_PASSWORD="${DATABASE_PASSWORD}" \
  DATABASE_NAME="${DATABASE_NAME}" \
  DATABASE_URL="postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}" \
  JWT_ACCESS_SECRET="${JWT_ACCESS_SECRET}" \
  JWT_REFRESH_SECRET="${JWT_REFRESH_SECRET}" \
  JWT_PASSWORD_RESET_SECRET="${JWT_PASSWORD_RESET_SECRET}" \
  REDIS_HOST="${REDIS_HOST}" \
  REDIS_PORT="${REDIS_PORT}" \
  REDIS_PASSWORD="${REDIS_PASSWORD}" \
  BUCKET_KEY="${BUCKET_KEY}" \
  BUCKET_SECRET="${BUCKET_SECRET}" \
  BUCKET_ENDPOINT="${BUCKET_ENDPOINT}" \
  BUCKET_NAME="${BUCKET_NAME}" \
  MAIL_HOST="${MAIL_HOST}" \
  MAIL_USER="${MAIL_USER}" \
  MAIL_PASSWORD="${MAIL_PASSWORD}" \
  MAIL_FROM="${MAIL_FROM}" \
  MAIL_PORT="${MAIL_PORT}" \
  YANDEX_CLIENT_ID="${YANDEX_CLIENT_ID}" \
  YANDEX_CLIENT_SECRET="${YANDEX_CLIENT_SECRET}" \
  YANDEX_BASE_URL="${YANDEX_BASE_URL}" \
  YANDEX_LOGIN_URL="${YANDEX_LOGIN_URL}"

EXPOSE ${PORT}

CMD ["sh", "docker-start-db.sh"]
