version: '3'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'listen_addresses=*', '-c', 'log_statement=all']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -U postgres']
      interval: 5s
      retries: 5
      start_period: 10s

  redis:
    image: 'redis:7-alpine'
    command: redis-server --requirepass redis_secret
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 3

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - '8000:8000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: postgresql://postgres:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_secret
    command: sh -c "yarn --ignore-engines && yarn generate && yarn migrate && yarn dev"
